(function(g){var window=this;var Uja=function(a,b){return g.cc(a,b)},Vja=function(a){if(a.hc&&"function"==typeof a.hc)return a.hc();
if(g.w(a))return a.split("");if(g.Ba(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Zb(a)},Wja=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ba(a)||g.w(a))(0,g.D)(a,b,void 0);else{if(a.rd&&"function"==typeof a.rd)var c=a.rd();else if(a.hc&&"function"==typeof a.hc)c=void 0;else if(g.Ba(a)||g.w(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.$b(a);d=Vja(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},i4=function(a){g.mp(a,"zx",g.Ib());
return a},j4=function(a,b,c){g.Aa(c)||(c=[String(c)]);
g.sp(a.o,b,c)},k4=function(){},l4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},m4=function(a){var b;
(b=a.g)||(b={},l4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},n4=function(a){return(a=l4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},o4=function(a,b){return b+" ["+a.ca+" "+a.I+" "+a.getStatus()+"]"},Xja=function(a){return"content-type"==a.toLowerCase()},p4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.x.clearTimeout(a.F),a.F=null)},Yja=function(a){return g.Id&&g.zc(9)&&g.wa(a.timeout)&&g.t(a.ontimeout)},q4=function(a){a.W||(a.W=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},r4=function(a,b){if(a.g){p4(a);
var c=a.g,d=a.P[0]?g.xa:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},s4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;q4(a);r4(a)},t4=function(a){return a.g?a.g.readyState:0},u4=function(a){if(a.l&&"undefined"!=typeof g.QV)if(a.P[1]&&4==t4(a)&&2==a.getStatus())o4(a,"Local request error detected and ignored");
else if(a.G&&4==t4(a))g.Ag(a.Ds,0,a);else if(a.dispatchEvent("readystatechange"),4==t4(a)){o4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(String(a.I))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Zja.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<t4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";q4(a)}}finally{r4(a)}}},v4=function(a){g.Ef.call(this);
this.headers=new g.$o;this.R=a||null;this.l=!1;this.P=this.g=null;this.ca=this.I="";this.A=0;this.B="";this.o=this.V=this.G=this.W=!1;this.C=0;this.F=null;this.Z="";this.L=this.X=!1},w4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},$ja=function(a,b){var c=[];
g.Gl(b,function(a){try{var b=g.rr.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.qr(b)&&c.push(a):c.push(a)},a);
return c},aka=function(a,b){var c=$ja(a,b);
(0,g.D)(c,function(a){g.rr.prototype.remove.call(this,a)},a)},bka=function(a,b,c,d){var e=new g.cp(null,void 0);
a&&g.dp(e,a);b&&g.ep(e,b);c&&g.fp(e,c);d&&(e.l=d);return e},x4=function(){this.g=[];
this.l=[]},y4=function(a){g.ru[a]&&(a=g.ru[a],(0,g.D)(a,function(a){g.pu[a]&&delete g.pu[a]}),a.length=0)},cka=function(a){var b=g.ou();
if(b)if(b.clear(a),a)y4(a);else for(var c in g.ru)y4(c)},z4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.$o;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",dka(this,a.capabilities||""),eka(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},dka=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.B(Uja,fka)).forEach(function(b){a.capabilities.add(b)})},eka=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},A4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},B4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},C4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},gka=function(a){return new A4(a)},D4=function(a){return g.Aa(a)?(0,g.G)(a,gka):[]},E4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},F4=function(a){return g.Aa(a)?"["+(0,g.G)(a,E4).join(",")+"]":"null"},G4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},hka=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},H4=function(a,b){return g.Oa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},I4=function(a,b){return g.Oa(a,function(a){return B4(a,b)})},ika=function(){var a=(0,g.lv)();
a&&aka(a,a.g.Qe(!0))},J4=function(){var a=g.ov("yt-remote-connected-devices")||[];
g.ib(a);return a},jka=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},K4=function(a){g.nv("yt-remote-connected-devices",a,86400)},M4=function(){if(L4)return L4;
var a=g.ov("yt-remote-device-id");a||(a=G4(),g.nv("yt-remote-device-id",a,31536E3));for(var b=J4(),c=1,d=a;g.Ta(b,d);)c++,d=a+"#"+c;return L4=d},N4=function(){var a=J4(),b=M4();
g.Ta(a,b);g.qv()&&g.nb(a,b);a=jka(a);if(0==a.length)try{g.Zu("remote_sid")}catch(c){}else try{g.Yu("remote_sid",a.join(","),-1)}catch(c){}},O4=function(){return g.ov("yt-remote-session-browser-channel")},P4=function(){return g.ov("yt-remote-local-screens")||[]},Q4=function(){g.nv("yt-remote-lounge-token-expiration",!0,86400)},kka=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(P4(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.Go)(c,function(a){return!g.Ta(b,a)})&&Q4();
g.nv("yt-remote-local-screens",a,31536E3)},lka=function(a,b){g.nv("yt-remote-session-browser-channel",a);
g.nv("yt-remote-session-screen-id",b);var c=J4(),d=M4();g.Ta(c,d)||c.push(d);K4(c);N4()},R4=function(a){a||(g.pv("yt-remote-session-screen-id"),g.pv("yt-remote-session-video-id"));
N4();a=J4();g.Xa(a,M4());K4(a)},T4=function(){if(!S4){var a=g.Dr();
a&&(S4=new g.lr(a))}return S4?!!S4.get("yt-remote-use-staging-server"):!1},mka=function(){var a=window.document.createElement("a");
g.hd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Mb(a)},nka=function(a,b){var c=g.Rd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.id(c,g.oe("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},oka=function(){var a=mka(),b=window.document.getElementById(a),c=b&&g.Ft(b,"loaded");
c||b&&!c||(b=nka(a,function(){g.Ft(b,"loaded")||(g.Et(b,"loaded","true"),g.wu(a),g.vs(g.B(cka,a),0))}))},U4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},V4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X4=function(a){a.length?W4(a.shift(),function(){X4(a)}):Y4()},pka=function(a){return"chrome-extension://"+a+Z4},W4=function(a,b,c){var d=
window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},$4=function(a){return 0<=window.navigator.userAgent.indexOf(a)},Y4=function(){var a=V4();
a&&a(!1,"No cast extension found")},a5=function(){if(qka){var a=2,b=V4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;W4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y4,c)}},rka=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(a5(),a({command:"cast.sender.init"}))},ska=function(){a5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X4(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+Z4,"//www.gstatic.com/eureka/clank"+Z4])},b5=function(a,b,c){g.I.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Bc=b;this.B=(0,g.A)(this.jA,this);this.g=!1;this.l=0;this.o=this.Aa=null;this.A=[]},c5=function(){},d5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.da=new g.tp(this);this.l=new g.zg;this.l.setInterval(250)},f5=function(a,b,c){a.uh=1;
a.Hf=i4(b.clone());a.Qg=c;a.B=!0;e5(a,null)},g5=function(a,b,c,d,e){a.uh=1;
a.Hf=i4(b.clone());a.Qg=null;a.B=c;e&&(a.Tw=!1);e5(a,d)},e5=function(a,b){a.Nh=(0,g.F)();
h5(a);a.Zf=a.Hf.clone();j4(a.Zf,"t",a.C);a.sj=0;a.gc=a.g.Sm(a.g.mj()?b:null);0<a.qn&&(a.xl=new g.um((0,g.A)(a.hy,a,a.gc),a.qn));a.da.ea(a.gc,"readystatechange",a.PJ);var c=a.yg?g.kc(a.yg):{};a.Qg?(a.Wl="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.gc.send(a.Zf,a.Wl,a.Qg,c)):(a.Wl="GET",a.Tw&&!g.Kd&&(c.Connection="close"),a.gc.send(a.Zf,a.Wl,null,c));a.g.ee(1)},o5=function(a,b,c){for(var d=!0;!a.og&&a.sj<c.length;){var e=tka(a,c);
if(e==i5){4==b&&(a.If=4,j5(15),d=!1);break}else if(e==k5){a.If=4;j5(16);d=!1;break}else l5(a,e)}4==b&&0==c.length&&(a.If=1,j5(17),d=!1);a.ge=a.ge&&d;d||(m5(a),n5(a))},tka=function(a,b){var c=a.sj,d=b.indexOf("\n",c);
if(-1==d)return i5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return k5;d+=1;if(d+c>b.length)return i5;var e=b.substr(d,c);a.sj=d+c;return e},r5=function(a,b){a.Nh=(0,g.F)();
h5(a);var c=b?window.location.hostname:"";a.Zf=a.Hf.clone();g.mp(a.Zf,"DOMAIN",c);g.mp(a.Zf,"t",a.C);try{a.he=new window.ActiveXObject("htmlfile")}catch(n){m5(a);a.If=7;j5(22);n5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in p5)k=p5[l];else if(l in q5)k=p5[l]=q5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
p5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.kd(g.Gc("b/12014412"),d);a.he.open();a.he.write(g.dd(c));a.he.close();a.he.parentWindow.m=(0,g.A)(a.iJ,a);a.he.parentWindow.d=(0,g.A)(a.ew,a,!0);a.he.parentWindow.rpcClose=(0,g.A)(a.ew,a,!1);c=a.he.createElement("DIV");a.he.parentWindow.document.body.appendChild(c);d=g.Rc(a.Zf.toString());d=g.Cb(g.Oc(d));d=g.kd(g.Gc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.dd(d);a.g.ee(1)},h5=function(a){a.fq=
(0,g.F)()+a.A;
s5(a,a.A)},s5=function(a,b){if(null!=a.Zh)throw Error("WatchDog timer not null");
a.Zh=t5((0,g.A)(a.tJ,a),b)},u5=function(a){a.Zh&&(g.x.clearTimeout(a.Zh),a.Zh=null)},n5=function(a){a.g.Bs()||a.og||a.g.nl(a)},m5=function(a){u5(a);
g.Ze(a.xl);a.xl=null;a.l.stop();g.vp(a.da);if(a.gc){var b=a.gc;a.gc=null;b.abort();b.dispose()}a.he&&(a.he=null)},l5=function(a,b){try{a.g.Yv(a,b),a.g.ee(4)}catch(c){}},w5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;v5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){w5(a,b,c,d,f)},f)})}},v5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{x5(d),c(!0)}catch(e){}};
d.onerror=function(){try{x5(d),c(!1)}catch(e){}};
d.onabort=function(){try{x5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{x5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},x5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},y5=function(a){this.g=a;
this.l=new c5},A5=function(a){var b=z5(a.g,a.hi,"/mail/images/cleardot.gif");
i4(b);w5(b.toString(),5E3,(0,g.A)(a.Jz,a),3,2E3);a.ee(1)},C5=function(a){var b=a.g.I;
if(null!=b)j5(5),b?(j5(11),B5(a.g,a,!1)):(j5(12),B5(a.g,a,!0));else if(a.zd=new d5(a,void 0,void 0,void 0),a.zd.yg=a.mn,b=a.g,b=z5(b,b.mj()?a.Bi:null,a.pn),j5(5),!g.Id||g.Cc(10))j4(b,"TYPE","xmlhttp"),g5(a.zd,b,!1,a.Bi,!1);else{j4(b,"TYPE","html");var c=a.zd;a=!!a.Bi;c.uh=3;c.Hf=i4(b.clone());r5(c,a)}},D5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new c5;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},uka=function(a,b){this.g=a;
this.map=b;this.context=null},E5=function(a){g.af.call(this,"statevent",a)},F5=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},G5=function(a){g.af.call(this,"serverreachability",a)},K5=function(a){H5(a);
if(3==a.g){var b=a.aj++,c=a.nk.clone();g.mp(c,"SID",a.o);g.mp(c,"RID",b);g.mp(c,"TYPE","terminate");I5(a,c);b=new d5(a,a.o,b,void 0);b.uh=2;b.Hf=i4(c.clone());(new window.Image).src=b.Hf;b.Nh=(0,g.F)();h5(b)}J5(a)},M5=function(a){a.Tz(1,0);
a.nk=z5(a,null,a.ln);L5(a)},H5=function(a){a.Bf&&(a.Bf.abort(),a.Bf=null);
a.Lb&&(a.Lb.cancel(),a.Lb=null);a.Se&&(g.x.clearTimeout(a.Se),a.Se=null);N5(a);a.dd&&(a.dd.cancel(),a.dd=null);a.Df&&(g.x.clearTimeout(a.Df),a.Df=null)},O5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new uka(a.BF++,b));2!=a.g&&3!=a.g||L5(a)},L5=function(a){a.dd||a.Df||(a.Df=t5((0,g.A)(a.cw,a),0),a.ph=0)},R5=function(a,b){if(1==a.g){if(!b){a.aj=Math.floor(1E5*Math.random());
var c=a.aj++,d=new d5(a,"",c,void 0);d.yg=null;var e=P5(a),f=a.nk.clone();g.mp(f,"RID",c);g.mp(f,"CVER","1");I5(a,f);f5(d,f,e);a.dd=d;a.g=2}}else 3==a.g&&(b?Q5(a,b):0==a.l.length||a.dd||Q5(a))},Q5=function(a,b){if(b)if(6<a.pg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.aj-1;var d=P5(a)}else c=b.F,d=b.Qg;else c=a.aj++,d=P5(a);var e=a.nk.clone();g.mp(e,"SID",a.o);g.mp(e,"RID",c);g.mp(e,"AID",a.zh);I5(a,e);c=new d5(a,a.o,c,a.ph+1);c.yg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.dd=c;f5(c,e,d)},I5=function(a,b){if(a.Hc){var c=a.Hc.ds();
c&&g.Ub(c,function(a,c){g.mp(b,c,a)})}},P5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.pg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.pg?e:f-d;try{g.Ub(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},S5=function(a){a.Lb||a.Se||(a.F=1,a.Se=t5((0,g.A)(a.bw,a),0),a.ih=0)},U5=function(a){if(a.Lb||a.Se||3<=a.ih)return!1;
a.F++;a.Se=t5((0,g.A)(a.bw,a),T5(a,a.ih));a.ih++;return!0},B5=function(a,b,c){a.Ul=c;
a.xe=b.Ze;a.C||M5(a)},N5=function(a){null!=a.rg&&(g.x.clearTimeout(a.rg),a.rg=null)},T5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W5=function(a,b){if(2==b||9==b){var c=null;
a.Hc&&(c=null);var d=(0,g.A)(a.uK,a);c||(c=new g.cp("//www.google.com/images/cleardot.gif"),i4(c));v5(c.toString(),1E4,d)}else j5(2);V5(a,b)},V5=function(a,b){a.g=0;
a.Hc&&a.Hc.jr(b);J5(a);H5(a)},J5=function(a){a.g=0;
a.xe=-1;if(a.Hc)if(0==a.A.length&&0==a.l.length)a.Hc.Km();else{g.$a(a.A);var b=g.$a(a.l);a.A.length=0;a.l.length=0;a.Hc.Km(b)}},z5=function(a,b,c){var d=g.np(c);
if(""!=d.g)b&&g.ep(d,b+"."+d.g),g.fp(d,d.B);else{var e=window.location;d=bka(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.oi&&g.Ub(a.oi,function(a,b){g.mp(d,b,a)});
g.mp(d,"VER",a.pg);I5(a,d);return d},t5=function(a,b){if(!g.Ca(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},j5=function(a){X5.dispatchEvent(new E5(X5,a))},Y5=function(){},vka=function(a,b){this.action=a;
this.params=b||{}},Z5=function(a,b){g.I.call(this);
this.g=new g.N(this.bJ,0,this);g.J(this,this.g);this.Bc=5E3;this.l=0;if(g.Ca(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ca(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},$5=function(a,b,c){this.L=a;
this.C=b;this.o=new g.gr;this.l=new Z5(this.TK,this);this.g=null;this.K=!1;this.B=null;this.I="";this.G=this.A=0;this.F=[];this.P=c||!1},wka=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ul,sessionId:a.g.o,arrayId:a.g.zh}},a6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&R5(a.g),K5(a.g));a.G=0},b6=function(a){return!!a.g&&3==a.g.g},xka=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},c6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Wg(a)||"";b&&(this.port=":"+b);this.domain=g.Vg(a)||"";a=g.Rb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Lb(a,"10.0")&&(this.l=!1))},d6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.eh(c+b,{})},e6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.B(a.A,d,!0),onError:g.B(a.o,e),Uc:g.B(a.B,e)};c&&(a.ib=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ms(b,a)},yka=function(){var a=f6;
g6();h6.push(a);i6(h6)},j6=function(a,b){g6();
var c=h6,d=zka(a,String(b));0==c.length?Aka(d):(i6(c),(0,g.D)(c,function(a){a(d)}))},g6=function(){h6||(h6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",h6,void 0))},Aka=function(a){var b=(k6+1)%50;
k6=b;l6[b]=a;m6||(m6=49==b)},i6=function(a){var b=l6;
if(b[0]){var c=k6,d=m6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
l6=Array(50);k6=-1;m6=!1}},zka=function(a,b){var c=((0,g.F)()-Bka)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n6=function(a){g.Q.call(this);
this.F=a;this.g=[]},o6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cka=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(a){return!!H4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=o6(a,b[d])||c;return c},Dka=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},p6=function(a,b,c,d){g.Q.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Aa=window.NaN},r6=function(a){n6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;q6(this);this.info("Initializing with "+F4(this.g))},s6=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=d6(a.o,"/pairing/get_lounge_token_batch");
e6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.uA,a),(0,g.A)(a.tA,a))}},q6=function(a){var b=D4(P4());
b=(0,g.Yd)(b,function(a){return!a.uuid});
return Cka(a,b)},t6=function(a,b){kka((0,g.G)(a.g,C4));
b&&Q4()},v6=function(a,b){g.Q.call(this);
this.C=b;var c=g.ov("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ta(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;u6("Initialized with "+g.Lg(this.g))},w6=function(a,b,c){var d=d6(a.B,"/pairing/get_screen_availability");
e6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},x6=function(a,b){a:if(g.Yb(b)!=g.Yb(a.g))var c=!1;
else{c=g.$b(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(u6("Updated online screens: "+g.Lg(a.g)),a.g=b,a.O("screenChange"));Eka(a)},y6=function(a){(0,window.isNaN)(a.o)||g.xs(a.o);
a.o=g.vs((0,g.A)(a.vp,a),0<a.A&&a.A<(0,g.F)()?2E4:1E4)},u6=function(a){j6("OnlineScreenService",a)},z6=function(a){var b={};
(0,g.D)(a.C(),function(a){a.token?b[a.token]=a.id:this.Ab("Requesting availability of screen w/o lounge token.")});
return b},Eka=function(a){a=g.$b(g.Vb(a.g,function(a){return a}));
g.ib(a);a.length?g.nv("yt-remote-online-screen-ids",a.join(","),60):g.pv("yt-remote-online-screen-ids")},A6=function(a){n6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};Fka(this)},C6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ud();if(k=(c?I4(k,c):null)||I4(k,b)){k.uuid=b;var l=B6(a,k);w6(a.l,l,function(a){e(a?l:null)})}else c?Gka(a,c,(0,g.A)(function(a){var f=B6(this,new A4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));w6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},D6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Gka=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ib:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ms(d6(a.C,"/pairing/get_lounge_token_batch"),e)},E6=function(a){a.g=a.o.ud();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+F4(a.g))},Fka=function(a){F6(a);
a.o=new r6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.HA,a));E6(a);a.A=D4(g.ov("yt-remote-automatic-screen-cache")||[]);F6(a);a.info("Initializing automatic screens: "+F4(a.A));a.l=new v6(a.C,(0,g.A)(a.ud,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.O("onlineScreenChange")},a))},B6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=I4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.nv("yt-remote-automatic-screen-cache",(0,g.G)(a.A,C4)));F6(a);a.B[b.uuid]=b.id;g.nv("yt-remote-device-id-map",a.B,31536E3);return b},F6=function(a){a.B=g.ov("yt-remote-device-id-map")||{}},G6=function(a,b,c){g.Q.call(this);
this.P=c;this.I=a;this.l=b;this.o=null},H6=function(a,b){j6(a.P,b)},J6=function(a,b){G6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.ZK,this);this.B=(0,g.A)(this.EJ,this);this.A=g.vs((0,g.A)(function(){I6(this,null)},this),12E4)},Hka=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.xa,(0,g.A)(function(){H6(this,"Failed to send message: getMdxSessionStatus.")},a)):H6(a,"Sending yt message without session: "+g.Lg(b))},I6=function(a,b){g.xs(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.ol,a),d=(0,g.A)(a.yd,a);a.ts(b,c,d,5)}}else a.yd(Error("Waiting for session status timed out."))},K6=function(a,b,c){G6.call(this,a,b,"DialSession");
this.A=this.G=null;this.K="";this.R=c;this.B=null;this.F=g.xa;this.C=window.NaN;this.L=(0,g.A)(this.cL,this);this.g=g.xa},L6=function(a){a.g=a.I.oy(a.K,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.xa;
this.ol(a)},a),(0,g.A)(function(a){this.g=g.xa;
this.yd(a)},a))},M6=function(a){var b={};
b.pairingCode=a.K;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}T4()&&(b.env_useStageMdx=1);return g.ch(b)},N6=function(a,b){G6.call(this,a,b,"ManualSession");
this.g=g.vs((0,g.A)(this.Bh,this,null),150)},O6=function(a,b,c,d){g.Q.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.oI,this)},P6=function(a,b){return b?g.Oa(a.o,function(a){return B4(b,a.label)},a):null},Q6=function(a){j6("Controller",a)},f6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},R6=function(a){return a.B||!!a.o.length||!!a.g},S6=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.l):a.O("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.aw,a,b)),b.o?a.O("yt-remote-cast2-session-change",b.o):c&&a.g.Bh(null)):a.O("yt-remote-cast2-session-change",null))},T6=function(a){var b=a.l.ny(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&B4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=P6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lka=function(a,b,c,d,e,f,k){Ika()?Jka(b,e,f,k)&&(V6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?W6(a,c):(window.__onGCastApiAvailable=function(b,d){b?W6(a,c):(X6("Failed to load cast API: "+d),Y6(!1),V6(!1),g.pv("yt-remote-cast-available"),g.pv("yt-remote-cast-receiver"),Z6(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):oka():$4("CriOS")?rka():$4("Android")&&$4("Chrome/")&&window.navigator.presentation?ska():window.chrome&&window.navigator.presentation&&!$4("Edge")?(a5(),X4(Kka.map(pka))):Y4())):U6("Cannot initialize because not running Chrome")},Z6=function(){U6("dispose");
var a=$6();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);a7(!1);g.uu(b7);b7.length=0},c7=function(){return!!g.ov("yt-remote-cast-installed")},d7=function(){var a=g.ov("yt-remote-cast-receiver");
return a?a.friendlyName:null},e7=function(){U6("clearCurrentReceiver");
g.pv("yt-remote-cast-receiver")},f7=function(){return c7()?$6()?$6().getCastSession():(X6("getCastSelector: Cast is not initialized."),null):(X6("getCastSelector: Cast API is not installed!"),null)},h7=function(){c7()?$6()?g7()?(U6("Requesting cast selector."),$6().requestSession()):(U6("Wait for cast API to be ready to request the session."),b7.push(g.tu("yt-remote-cast2-api-ready",h7))):X6("requestCastSelector: Cast is not initialized."):X6("requestCastSelector: Cast API is not installed!")},i7=
function(a,b){g7()?$6().setConnectedScreenStatus(a,b):X6("setConnectedScreenStatus called before ready.")},Ika=function(){var a=0<=g.Rb.search(/ (CrMo|Chrome|CriOS)\//);
return g.aw||a},Mka=function(a,b){$6().init(a,b)},Jka=function(a,b,c,d){var e=!1;
$6()||(a=new O6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.nv("yt-remote-cast-available",a);g.xu("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){U6("onReceiverSelected: "+a.friendlyName);
g.nv("yt-remote-cast-receiver",a);g.xu("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){U6("onReceiverResumed: "+a.friendlyName);
g.nv("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){U6("onSessionChange: "+E4(a));
a||g.pv("yt-remote-cast-receiver");g.xu("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
U6("cloudview.createSingleton_: "+e);return e},$6=function(){return g.z("yt.mdx.remote.cloudview.instance_")},W6=function(a,b){Y6(!0);
V6(!1);Mka(a,function(a){a?(a7(!0),g.wu("yt-remote-cast2-api-ready")):(X6("Failed to initialize cast API."),Y6(!1),g.pv("yt-remote-cast-available"),g.pv("yt-remote-cast-receiver"),Z6());b(a)})},U6=function(a){j6("cloudview",a)},X6=function(a){j6("cloudview",a)},Y6=function(a){U6("setCastInstalled_ "+a);
g.nv("yt-remote-cast-installed",a)},g7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},a7=function(a){U6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},V6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},j7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.l=null;this.hasNext=this.ye=!1;this.K=this.I=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},k7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.ye=!1;a.hasNext=!1;a.G=0;a.F=(0,g.F)();a.B=0;a.o=0;a.I=0;a.K=0;a.A=window.NaN;a.C=!1},l7=function(a){return 1==a.g?((0,g.F)()-a.F)/1E3:0},m7=function(a,b){a.G=b;
a.F=(0,g.F)()},n7=function(a){switch(a.g){case 1:case 1081:return((0,g.F)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},o7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&k7(a)},p7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.lc(a.l);b.hasPrevious=a.ye;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.A;return b},s7=function(a,b){g.Q.call(this);
this.g=0;this.A=a;this.C=[];this.B=new x4;this.o=this.l=null;this.I=(0,g.A)(this.iG,this);this.F=(0,g.A)(this.dj,this);this.G=(0,g.A)(this.hG,this);this.K=(0,g.A)(this.vG,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.hq,this),q7(this))):c=3;0!=c&&(b?this.hq(c):g.vs((0,g.A)(function(){this.hq(c)},this),0));
var d=f7();d&&r7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},t7=function(a){return new j7(a.A.getPlayerContextData())},q7=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.B(this.lI,a),this))},a)},u7=function(a){(0,g.D)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},v7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},x7=function(a,b,c){var d=t7(a);
m7(d,c);-1E3!=d.g&&(d.g=b);w7(a,d)},y7=function(a,b,c){a.A.sendMessage(b,c)},w7=function(a,b){u7(a);
a.A.setPlayerContextData(p7(b));q7(a)},r7=function(a,b){a.o&&(a.o.removeUpdateListener(a.I),a.o.removeMediaListener(a.F),a.dj(null));
a.o=b;a.o&&(j6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.I),a.o.addMediaListener(a.F),a.o.media.length&&a.dj(a.o.media[0]))},z7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=t7(a);b.contentId!=d.videoId&&j6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;m7(d,a.l.getEstimatedTime());w7(a,d)}else j6("CP","No cast media video. Ignoring state update.")},A7=function(a,b,c){return(0,g.A)(function(a){this.Ab("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Ab("Retrying "+b+" using MDx browser channel."),y7(this,b,c))},a)},B7=function(a,b,c){g.Q.call(this);
this.B=window.NaN;this.R=!1;this.K=this.I=this.L=this.P=window.NaN;this.W=[];this.A=this.F=this.o=this.Na=this.g=null;this.va=a;this.W.push(g.Tt(window,"beforeunload",(0,g.A)(this.nA,this)));this.l=[];this.Na=new j7;this.V=b.id;this.g=Nka(this,c);this.g.subscribe("handlerOpened",this.mG,this);this.g.subscribe("handlerClosed",this.jG,this);this.g.subscribe("handlerError",this.kG,this);this.g.subscribe("handlerMessage",this.lG,this);xka(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Na.videoId;g.qv()&&g.nv("yt-remote-session-video-id",a)},this)},C7=function(a){j6("conn",a)},Nka=function(a,b){return new $5(d6(a.va,"/bc"),b)},D7=function(a,b){a.O("proxyStateChange",b)},Oka=function(a){a.B=g.vs((0,g.A)(function(){C7("Connecting timeout");
this.C(1)},a),2E4)},E7=function(a){g.xs(a.B);
a.B=window.NaN},F7=function(a){g.xs(a.P);
a.P=window.NaN},Pka=function(a){G7(a);
a.L=g.vs((0,g.A)(function(){H7(this,"getNowPlaying")},a),2E4)},G7=function(a){g.xs(a.L);
a.L=window.NaN},J7=function(a,b){b&&(E7(a),F7(a));
b==(b6(a.g)&&(0,window.isNaN)(a.B))?b&&(D7(a,1),H7(a,"getSubtitlesTrack")):b?(a.X()&&a.Na.reset(),D7(a,1),H7(a,"getNowPlaying"),I7(a)):a.C(1)},Qka=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Na.videoId&&(g.fc(b.params)?a.Na.l=null:a.Na.l=b.params,a.O("remotePlayerChange"))},K7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Na.listId=b.params.listId||a.Na.listId;o7(a.Na,c,d);a.O("remoteQueueChange")},Rka=function(a,b){b.params=b.params||{};
K7(a,b);L7(a,b);a.O("autoplayDismissed")},L7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
m7(a.Na,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Na.g&&(c=-1E3);a.Na.g=c;c=Number(b.params.loadedTime);a.Na.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Na.I=(0,window.isNaN)(c)?0:c;c=a.Na;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Na;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Na.g?Pka(a):G7(a);
a.O("remotePlayerChange")},Ska=function(a,b){if(-1E3!=a.Na.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Na.g=c;c=(0,window.parseInt)(b.params.currentTime,10);m7(a.Na,(0,window.isNaN)(c)?0:c);a.O("remotePlayerChange")}},Tka=function(a,b){var c="true"==b.params.muted;
a.Na.volume=(0,window.parseInt)(b.params.volume,10);a.Na.muted=c;a.O("remotePlayerChange")},Uka=function(a,b){a.F=b.params.videoId;
a.O("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Vka=function(a,b){var c="true"==b.params.hasNext;
a.Na.ye="true"==b.params.hasPrevious;a.Na.hasNext=c;a.O("previousNextChange")},I7=function(a){g.xs(a.K);
a.K=g.vs((0,g.A)(a.C,a,1),864E5)},H7=function(a,b,c){c?C7("Sending: action="+b+", params="+g.Lg(c)):C7("Sending: action="+b);
a.g.sendMessage(b,c)},M7=function(a){n6.call(this,"ScreenServiceProxy");
this.Ac=a;this.l=[];this.l.push(this.Ac.$_s("screenChange",(0,g.A)(this.XK,this)));this.l.push(this.Ac.$_s("onlineScreenChange",(0,g.A)(this.SH,this)))},$ka=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ns("MDX_CONFIG")||b;ika();N4();N7||(N7=new c6(b?b.loungeApiHost:void 0),T4()&&(N7.g="/api/loungedev"));O7||(O7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",O7,void 0));Wka();var c=P7();if(!c){var d=new A6(N7);g.y("yt.mdx.remote.screenService_",d,void 0);c=P7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lka(a,d,function(a){a?Q7()&&i7(Q7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.xu("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),R7("Initializing: "+g.Lg(b)),S7.push(g.tu("yt-remote-cast2-availability-change",function(){g.xu("yt-remote-receiver-availability-change")})),S7.push(g.tu("yt-remote-cast2-receiver-selected",function(){T7(null);
g.xu("yt-remote-auto-connect","cast-selector-receiver")})),S7.push(g.tu("yt-remote-cast2-receiver-resumed",function(){g.xu("yt-remote-receiver-resumed","cast-selector-receiver")})),S7.push(g.tu("yt-remote-cast2-session-change",Xka)),S7.push(g.tu("yt-remote-connection-change",function(a){a?i7(Q7(),"YouTube TV"):U7()||(i7(null,null),e7())})),a=V7(),b.isAuto&&(a.id+="#dial"),g.mu("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),R7(" -- with channel params: "+
g.Lg(a)),Yka(a),c.start(),Q7()||Zka())},ala=function(){var a=W7();
c7()&&g.ov("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},W7=function(){var a=P7().Ac.$_gos();
var b=X7();b&&Y7()&&(H4(a,b)||a.push(b));return hka(a)},Z7=function(){var a=bla();
!a&&c7()&&d7()&&(a={key:"cast-selector-receiver",name:d7()});return a},bla=function(){var a=W7(),b=X7();
b||(b=U7());return g.Oa(a,function(a){return b&&B4(b,a.key)?!0:!1})},X7=function(){var a=Q7();
if(!a)return null;var b=P7().ud();return I4(b,a)},Xka=function(a){R7("remote.onCastSessionChange_: "+E4(a));
if(a){var b=X7();b&&b.id==a.id?i7(b.id,"YouTube TV"):(b&&$7(),a8(a,1))}else Y7()&&$7()},$7=function(){g7()?$6().stopSession():X6("stopSession called before API ready.");
var a=Y7();a&&(a.disconnect(1),b8(null))},c8=function(){var a=Y7();
return!!a&&3!=a.getProxyState()},R7=function(a){j6("remote",a)},P7=function(){if(!d8){var a=g.z("yt.mdx.remote.screenService_");
d8=a?new M7(a):null}return d8},Q7=function(){return g.z("yt.mdx.remote.currentScreenId_")},e8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},f8=function(){return g.z("yt.mdx.remote.connectData_")},T7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},Y7=function(){return g.z("yt.mdx.remote.connection_")},b8=function(a){var b=Y7();
T7(null);a||e8("");g.y("yt.mdx.remote.connection_",a,void 0);O7&&((0,g.D)(O7,function(b){b(a)}),O7.length=0);
b&&!a?g.xu("yt-remote-connection-change",!1):!b&&a&&g.xu("yt-remote-connection-change",!0)},U7=function(){var a=g.qv();
if(!a)return null;var b=P7().ud();return I4(b,a)},a8=function(a,b){X7()&&X7();
e8(a.id);var c=new B7(N7,a,V7());c.connect(b,f8());c.subscribe("beforeDisconnect",function(a){g.xu("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Y7()&&b8(null)});
b8(c)},Zka=function(){var a=U7();
a?(R7("Resume connection to: "+E4(a)),a8(a,0)):(R4(),e7(),R7("Skipping connecting because no session screen found."))},Wka=function(){var a=V7();
if(g.fc(a)){a=M4();var b=g.ov("yt-remote-session-name")||"",c=g.ov("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},V7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Yka=function(a){a?(g.nv("yt-remote-session-app",a.app),g.nv("yt-remote-session-name",a.name)):(g.pv("yt-remote-session-app"),g.pv("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},g8=function(a,b,c){g.I.call(this);
this.G=a;this.l=b;this.o=new g.eu(this);g.J(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.mH);this.o.M(b,"captionschanged",this.gG);this.o.M(b,"captionssettingschanged",this.xx);this.o.M(b,"videoplayerreset",this.pl);this.o.M(b,"mdxautoplaycancel",this.Iz);this.W=this.o.M(b,"onVolumeChange",this.Ov);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.Xv,this);c.subscribe("remotePlayerChange",this.ej,this);c.subscribe("remoteQueueChange",this.pl,this);c.subscribe("autoplayUpNext",this.zv,
this);c.subscribe("previousNextChange",this.Uv,this);c.subscribe("nowAutoplaying",this.Qv,this);c.subscribe("autoplayDismissed",this.yv,this);this.suggestion=null;this.I=new g.SD(64);this.A=new g.N(this.tx,500,this);g.J(this,this.A);this.B=new g.N(this.vx,1E3,this);g.J(this,this.B);this.L=new b5(this.EK,0,this);g.J(this,this.L);this.C={};this.P=new g.N(this.Yx,1E3,this);g.J(this,this.P);this.K=new g.um(this.dE,1E3,this);g.J(this,this.K);this.R=g.xa;this.xx();this.pl();this.ej()},h8=function(a,b){var c=
a.G,d=a.l.ba().lengthSeconds;
c.F=b||0;c.g.O("progresssync",b,d)},j8=function(a){h8(a,0);
a.A.stop();i8(a,new g.SD(64))},l8=function(a,b){if(k8(a)&&!a.F){var c=null;
b&&(c={style:a.l.Mg()},g.nc(c,b));a.g.lx(a.l.ba(1).videoId,c);a.C=t7(a.g).l}},m8=function(a,b){var c=a.l.He();
if(c){var d=c.Ra;var e=c.listId.toString()}var f=a.l.ba(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.xh;var m=t7(c);l=l||0;var n={videoId:k,currentIndex:l};o7(m,k,l);g.t(b)&&(m7(m,b),n.currentTime=b);g.t(e)&&(n.listId=e);null!=d&&(n.playerParams=d);null!=f&&(n.clickTrackingParams=f);y7(c,"setPlaylist",n);e||w7(c,m);i8(a,new g.SD(1))},n8=function(a,b){if(b){var c=a.l.Ob("captions","tracklist",{Vs:1});
c&&c.length?(a.l.Tc("captions","track",b),a.F=!1):(a.l.Eh("captions"),a.F=!0)}else a.l.Tc("captions","track",{})},k8=function(a){return t7(a.g).videoId==a.l.ba(1).videoId},i8=function(a,b){a.B.stop();
var c=a.I;if(!g.$D(c,b)){var d=g.U(b,2);d!=g.U(a.I,2)&&g.lK(a.l,d);a.I=b;o8(a.G,c,b)}},q8=function(a){g.T.call(this,{D:"div",
J:"ytp-remote",H:[{D:"div",J:"ytp-remote-display-status",H:[{D:"div",J:"ytp-remote-display-status-icon",H:[g.$N()]},{D:"div",J:"ytp-remote-display-status-text",H:["{{statustext}}"]}]}]});this.g=new g.VO(this,250);g.J(this,this.g);this.l=a;this.M(a,"presentingplayerstatechange",this.o);p8(this,g.iK(a))},p8=function(a,b){if(3==a.l.Ha()){var c={RECEIVER_NAME:a.l.Ob("remote","currentReceiver").name};
c=g.U(b,128)?g.R("YTP_MDX_STATUS_ERROR_2",c):g.aE(b)||g.U(b,4)?g.R("YTP_MDX_STATUS_PLAYING_2",c):g.R("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.g.show()}else a.g.hide()},r8=function(a,b){g.oT.call(this,g.R("YTP_MDX_TITLE"),0,a,b);
this.g=a;this.F={};this.M(a,"onMdxReceiversChange",this.I);this.M(a,"presentingplayerstatechange",this.I);this.I()},s8=function(a){g.OK.call(this,a);
g.tv({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:G4(),name:g.R("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.K=this.l=null;this.I=[this.o];this.A=this.o;this.G=new g.SD(64);this.F=0;if(!g.iB(g.V(this.g))){a=
this.g;var b=g.ox(a);b&&(b=b.Qk())&&(b=new r8(a,b),g.J(this,b));b=new q8(a);g.J(this,b);g.DK(a,b.element,4)}},o8=function(a,b,c){a.G=c;
a.g.O("presentingplayerstatechange",new g.gE(c,b))},t8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)$7();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ba(1),e=d.videoId;if(c||e){var f=a.g.He();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Db(l).videoId}else k=[e];f=a.g.ya(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.xh,index:Math.max(a.g.bu(),0),currentTime:0==f?void 0:f}}else c=null;R7("Connecting to: "+g.Lg(b));"cast-selector-receiver"==b.key?(T7(c||null),g7()?$6().setLaunchParams(c||null):X6("setLaunchParams called before ready.")):!c&&c8()&&Q7()==
b.key?g.xu("yt-remote-connection-change",!0):($7(),T7(c||null),c=P7().ud(),(c=I4(c,b.key))&&a8(c,1))}},Zja=/^https?$/i,dla=["POST",
"PUT"];g.C(v4,g.Ef);g.h=v4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.B="";this.A=0;this.ca=b;this.W=!1;this.l=!0;this.g=this.R?n4(this.R):n4(g.PW);this.P=this.R?m4(this.R):m4(g.PW);this.g.onreadystatechange=(0,g.A)(this.Ds,this);try{k4(o4(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){k4(o4(this,"Error opening Xhr: "+f.message));s4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Wja(d,function(a,b){e.set(b,a)});
d=g.Oa(e.rd(),Xja);c=g.x.FormData&&a instanceof g.x.FormData;!g.Ta(dla,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.X&&(this.g.withCredentials=this.X);try{p4(this),0<this.C&&(this.L=Yja(this.g),k4(o4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.Es,this)):this.F=g.Ag(this.Es,this.C,this)),k4(o4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){k4(o4(this,"Send error: "+f.message)),s4(this,f)}};
g.h.Es=function(){"undefined"!=typeof g.QV&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,o4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(o4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),r4(this))};
g.h.T=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),r4(this,!0));v4.xa.T.call(this)};
g.h.Ds=function(){this.ga()||(this.V||this.G||this.o?u4(this):this.nI())};
g.h.nI=function(){u4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<t4(this)?this.g.status:-1}catch(a){return-1}};
var q5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},p5={"'":"\\'"},ela={};g.h=x4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Ta(this.g,a)||g.Ta(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Vfa)(b,a);0<=c?(g.Wa(b,c),b=!0):b=!1;return b||g.Xa(this.l,a)};
g.h.hc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var fka={mL:"atp",vN:"ska",jN:"que",KM:"mus",uN:"sus",dM:"dsp"};z4.prototype.Yj=function(){var a=new z4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var S4,L4="",Z4=U4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",qka=U4("loadCastFramework")||U4("loadCastApplicationFramework"),Kka=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(b5,g.I);g.h=b5.prototype;g.h.iA=function(a){this.A=arguments;this.g=!1;this.Aa?this.o=(0,g.F)()+this.Bc:this.Aa=g.Ag(this.B,this.Bc)};
g.h.stop=function(){this.Aa&&(g.x.clearTimeout(this.Aa),this.Aa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.T=function(){this.stop();b5.xa.T.call(this)};
g.h.jA=function(){this.o?(this.Aa=g.Ag(this.B,this.o-(0,g.F)()),this.o=null):(this.Aa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};c5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
c5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=d5.prototype;g.h.yg=null;g.h.ge=!1;g.h.Zh=null;g.h.fq=null;g.h.Nh=null;g.h.uh=null;g.h.Hf=null;g.h.Zf=null;g.h.Qg=null;g.h.gc=null;g.h.sj=0;g.h.he=null;g.h.Wl=null;g.h.If=null;g.h.Ci=-1;g.h.Tw=!0;g.h.og=!1;g.h.qn=0;g.h.xl=null;var k5={},i5={};g.h=d5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.PJ=function(a){a=a.target;var b=this.xl;b&&3==t4(a)?b.sh():this.hy(a)};
g.h.hy=function(a){try{if(a==this.gc)a:{var b=t4(this.gc),c=this.gc.A,d=this.gc.getStatus();if(g.Id&&!g.Cc(10)||g.Kd&&!g.zc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Kh&&!w4(this.gc))break a;this.og||4!=b||7==c||(8==c||0>=d?this.g.ee(3):this.g.ee(2));u5(this);var e=this.gc.getStatus();this.Ci=e;var f=w4(this.gc);(this.ge=200==e)?(4==b&&m5(this),this.B?(o5(this,b,f),g.Kh&&this.ge&&3==b&&(this.da.ea(this.l,"tick",this.LJ),this.l.start())):l5(this,f),this.ge&&!this.og&&(4==b?this.g.nl(this):(this.ge=
!1,h5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.If=3,j5(13)):(this.If=0,j5(14)),m5(this),n5(this))}}catch(k){this.gc&&w4(this.gc)}finally{}};
g.h.LJ=function(){var a=t4(this.gc),b=w4(this.gc);this.sj<b.length&&(u5(this),o5(this,a,b),this.ge&&4!=a&&h5(this))};
g.h.iJ=function(a){t5((0,g.A)(this.hJ,this,a),0)};
g.h.hJ=function(a){this.og||(u5(this),l5(this,a),h5(this))};
g.h.ew=function(a){t5((0,g.A)(this.gJ,this,a),0)};
g.h.gJ=function(a){this.og||(m5(this),this.ge=a,this.g.nl(this),this.g.ee(4))};
g.h.cancel=function(){this.og=!0;m5(this)};
g.h.tJ=function(){this.Zh=null;var a=(0,g.F)();0<=a-this.fq?(2!=this.uh&&this.g.ee(3),m5(this),this.If=2,j5(18),n5(this)):s5(this,this.fq-a)};g.h=y5.prototype;g.h.mn=null;g.h.zd=null;g.h.yl=!1;g.h.Cs=null;g.h.jk=null;g.h.nn=null;g.h.pn=null;g.h.Id=null;g.h.Ze=-1;g.h.Bi=null;g.h.hi=null;g.h.connect=function(a){this.pn=a;a=z5(this.g,null,this.pn);j5(3);this.Cs=(0,g.F)();var b=this.g.G;null!=b?(this.Bi=b[0],(this.hi=b[1])?(this.Id=1,A5(this)):(this.Id=2,C5(this))):(j4(a,"MODE","init"),this.zd=new d5(this,void 0,void 0,void 0),this.zd.yg=this.mn,g5(this.zd,a,!1,null,!0),this.Id=0)};
g.h.Jz=function(a){if(a)this.Id=2,C5(this);else{j5(4);var b=this.g;b.xe=b.Bf.Ze;W5(b,9)}a&&this.ee(2)};
g.h.Sm=function(a){return this.g.Sm(a)};
g.h.abort=function(){this.zd&&(this.zd.cancel(),this.zd=null);this.Ze=-1};
g.h.Bs=function(){return!1};
g.h.Yv=function(a,b){this.Ze=a.Ci;if(0==this.Id)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.xe=this.Ze;W5(c,2);return}this.Bi=c[0];this.hi=c[1]}else c=this.g,c.xe=this.Ze,W5(c,2);else if(2==this.Id)if(this.yl)j5(7),this.nn=(0,g.F)();else if("11111"==b){if(j5(6),this.yl=!0,this.jk=(0,g.F)(),c=this.jk-this.Cs,!g.Id||g.Cc(10)||500>c)this.Ze=200,this.zd.cancel(),j5(12),B5(this.g,this,!0)}else j5(8),this.jk=this.nn=(0,g.F)(),this.yl=!1};
g.h.nl=function(){this.Ze=this.zd.Ci;if(this.zd.ge)0==this.Id?this.hi?(this.Id=1,A5(this)):(this.Id=2,C5(this)):2==this.Id&&((!g.Id||g.Cc(10)?!this.yl:200>this.nn-this.jk)?(j5(11),B5(this.g,this,!1)):(j5(12),B5(this.g,this,!0)));else{0==this.Id?j5(9):2==this.Id&&j5(10);var a=this.g;a.xe=this.Ze;W5(a,2)}};
g.h.mj=function(){return this.g.mj()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ee=function(a){this.g.ee(a)};g.h=D5.prototype;g.h.oi=null;g.h.dd=null;g.h.Lb=null;g.h.ln=null;g.h.nk=null;g.h.Yq=null;g.h.zk=null;g.h.aj=0;g.h.BF=0;g.h.Hc=null;g.h.Df=null;g.h.Se=null;g.h.rg=null;g.h.Bf=null;g.h.Ul=null;g.h.zh=-1;g.h.vt=-1;g.h.xe=-1;g.h.ph=0;g.h.ih=0;g.h.pg=8;var X5=new g.Ef;g.C(E5,g.af);g.C(F5,g.af);g.C(G5,g.af);g.h=D5.prototype;g.h.connect=function(a,b,c,d,e){j5(0);this.ln=b;this.oi=c||{};d&&g.t(e)&&(this.oi.OSID=d,this.oi.OAID=e);this.C?(t5((0,g.A)(this.zr,this,a),100),M5(this)):this.zr(a)};
g.h.zr=function(a){this.Bf=new y5(this);this.Bf.mn=null;this.Bf.l=this.B;this.Bf.connect(a)};
g.h.Bs=function(){return 0==this.g};
g.h.cw=function(a){this.Df=null;R5(this,a)};
g.h.bw=function(){this.Se=null;this.Lb=new d5(this,this.o,"rpc",this.F);this.Lb.yg=null;this.Lb.qn=0;var a=this.Yq.clone();g.mp(a,"RID","rpc");g.mp(a,"SID",this.o);g.mp(a,"CI",this.Ul?"0":"1");g.mp(a,"AID",this.zh);I5(this,a);if(!g.Id||g.Cc(10))g.mp(a,"TYPE","xmlhttp"),g5(this.Lb,a,!0,this.zk,!1);else{g.mp(a,"TYPE","html");var b=this.Lb,c=!!this.zk;b.uh=3;b.Hf=i4(a.clone());r5(b,c)}};
g.h.Yv=function(a,b){if(0!=this.g&&(this.Lb==a||this.dd==a))if(this.xe=a.Ci,this.dd==a&&3==this.g)if(7<this.pg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.Aa(c)&&3==c.length)if(0==c[0])a:{if(!this.Se){if(this.Lb)if(this.Lb.Nh+3E3<this.dd.Nh)N5(this),this.Lb.cancel(),this.Lb=null;else break a;U5(this);j5(19)}}else this.vt=c[1],0<this.vt-this.zh&&37500>c[2]&&this.Ul&&0==this.ih&&!this.rg&&(this.rg=t5((0,g.A)(this.cG,this),6E3));else W5(this,11)}else b!=ela.NL.g&&W5(this,11);else if(this.Lb==a&&
N5(this),!g.sb(b)){c=this.B.parse(b);g.Aa(c);for(var d=0;d<c.length;d++){var e=c[d];this.zh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.zk=e[2],e=e[3],null!=e?this.pg=e:this.pg=6,this.g=3,this.Hc&&this.Hc.lr(),this.Yq=z5(this,this.mj()?this.zk:null,this.ln),S5(this)):"stop"==e[0]&&W5(this,7):3==this.g&&("stop"==e[0]?W5(this,7):"noop"!=e[0]&&this.Hc&&this.Hc.kr(e),this.ih=0)}}};
g.h.cG=function(){null!=this.rg&&(this.rg=null,this.Lb.cancel(),this.Lb=null,U5(this),j5(20))};
g.h.nl=function(a){if(this.Lb==a){N5(this);this.Lb=null;var b=2}else if(this.dd==a)this.dd=null,b=1;else return;this.xe=a.Ci;if(0!=this.g)if(a.ge)1==b?(b=(0,g.F)()-a.Nh,X5.dispatchEvent(new F5(X5,a.Qg?a.Qg.length:0,b,this.ph)),L5(this),this.A.length=0):S5(this);else{var c=a.If,d;if(!(d=3==c||7==c||0==c&&0<this.xe)){if(d=1==b)this.dd||this.Df||1==this.g||2<=this.ph?d=!1:(this.Df=t5((0,g.A)(this.cw,this,a),T5(this,this.ph)),this.ph++,d=!0);d=!(d||2==b&&U5(this))}if(d)switch(c){case 1:W5(this,5);break;
case 4:W5(this,10);break;case 3:W5(this,6);break;case 7:W5(this,12);break;default:W5(this,2)}}};
g.h.Tz=function(a){if(!g.Ta(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.uK=function(a){a?j5(2):(j5(1),V5(this,8))};
g.h.Sm=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new v4;a.X=!1;return a};
g.h.isActive=function(){return!!this.Hc&&this.Hc.isActive(this)};
g.h.ee=function(a){X5.dispatchEvent(new G5(X5,a))};
g.h.mj=function(){return!(!g.Id||g.Cc(10))};
g.h=Y5.prototype;g.h.lr=function(){};
g.h.kr=function(){};
g.h.jr=function(){};
g.h.Km=function(){};
g.h.ds=function(){return{}};
g.h.isActive=function(){return!0};g.C(Z5,g.I);g.h=Z5.prototype;g.h.bJ=function(){this.Bc=Math.min(3E5,2*this.Bc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Bc+15E3*Math.random();g.Oq(this.g,a);this.l=(0,g.F)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Bc=5E3};g.C($5,Y5);g.h=$5.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ec=function(a){return this.o.Ec(a)};
g.h.O=function(a,b){return this.o.O.apply(this.o,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.Ze(this.o),a6(this),g.Ze(this.l),this.l=null)};
g.h.ga=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new D5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.g;e&&(e.Hc=null);d.Hc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.zh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.nc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):b6(this)&&O5(this.g,c)};
g.h.lr=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)O5(this.g,a[b])}this.O("handlerOpened")};
g.h.jr=function(a){var b=2==a&&401==this.g.xe;4==a||b||this.l.start();this.O("handlerError",a)};
g.h.Km=function(a){if(!this.l.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.ds=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.nc(a,this.B);return a};
g.h.kr=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),K5(this.g)):this.O("handlerMessage",new vka(a[0],a[1]))};
g.h.TK=function(){this.l.isActive();var a=this.g,b=0;a.Lb&&b++;a.dd&&b++;0!=b||this.connect(this.B,this.A)};c6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
c6.prototype.B=function(a){a(Error("request timed out"))};var Bka=(0,g.F)(),h6=null,l6=Array(50),k6=-1,m6=!1;g.C(n6,g.Q);n6.prototype.ud=function(){return this.g};
n6.prototype.contains=function(a){return!!H4(this.g,a)};
n6.prototype.get=function(a){return a?I4(this.g,a):null};
n6.prototype.info=function(a){j6(this.F,a)};g.C(p6,g.Q);var u8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=p6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.my()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.xs(this.Aa),this.Aa=window.NaN)};
g.h.T=function(){this.stop();p6.xa.T.call(this)};
g.h.my=function(){this.Aa=window.NaN;this.g=g.Ms(d6(this.C,"/pairing/get_screen"),{method:"POST",ib:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.A)(this.VK,this),onError:(0,g.A)(this.UK,this),Uc:(0,g.A)(this.WK,this)})};
g.h.VK=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.O("pairingComplete",new A4(c))};
g.h.UK=function(a){this.g=null;a.status&&404==a.status?this.l>=u8.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=u8[this.l],this.Aa=g.vs((0,g.A)(this.my,this),a),this.l++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.WK=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};g.C(r6,n6);g.h=r6.prototype;g.h.start=function(){q6(this)&&this.O("screenChange");!g.ov("yt-remote-lounge-token-expiration")&&s6(this);g.xs(this.l);this.l=g.vs((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){q6(this);o6(this,a);t6(this,!1);this.O("screenChange");b(a);a.token||s6(this)};
g.h.remove=function(a,b){var c=q6(this);Dka(this,a)&&(t6(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.Ql=function(a,b,c,d){var e=q6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.T=function(){g.xs(this.l);r6.xa.T.call(this)};
g.h.uA=function(a){q6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t6(this,!b);b&&j6(this.F,"Missed "+b+" lounge tokens.")};
g.h.tA=function(a){j6(this.F,"Requesting lounge tokens failed: "+a)};g.C(v6,g.Q);g.h=v6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.ov("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.F)()-144E5<a?0:a)?y6(this):(this.A=(0,g.F)()+3E5,g.nv("yt-remote-fast-check-period",this.A),this.vp())};
g.h.isEmpty=function(){return g.fc(this.g)};
g.h.update=function(){u6("Updating availability on schedule.");var a=this.C(),b=g.Vb(this.g,function(b,d){return b&&!!I4(a,d)},this);
x6(this,b)};
g.h.T=function(){g.xs(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);v6.xa.T.call(this)};
g.h.vp=function(){g.xs(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=z6(this);if(g.Yb(a)){var b=d6(this.B,"/pairing/get_screen_availability");this.l=e6(this.B,b,{lounge_token:g.$b(a).join(",")},(0,g.A)(this.HI,this,a),(0,g.A)(this.GI,this))}else x6(this,{}),y6(this)};
g.h.HI=function(a,b){this.l=null;var c=g.$b(z6(this));if(g.lb(c,g.$b(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x6(this,d);y6(this)}else this.Ab("Changing Screen set during request."),this.vp()};
g.h.GI=function(a){this.Ab("Screen availability failed: "+a);this.l=null;y6(this)};
g.h.Ab=function(a){j6("OnlineScreenService",a)};g.C(A6,n6);g.h=A6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.O("screenChange"),this.l.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Ql=function(a,b,c,d){this.o.contains(a)?this.o.Ql(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j6(this.F,a),d(Error(a)))};
g.h.ud=function(a){return a?this.g:g.Za(this.g,(0,g.Yd)(this.A,function(a){return!this.contains(a)},this))};
g.h.ny=function(){return(0,g.Yd)(this.ud(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.oy=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ze(f);d(B6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.YK=function(a,b,c,d){g.Ms(d6(this.C,"/pairing/get_screen"),{method:"POST",ib:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new A4(d.screen||{});if(!e.name||D6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);D6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(B6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Uc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.Ze(this.o);g.Ze(this.l);A6.xa.T.call(this)};
g.h.HA=function(){E6(this);this.O("screenChange");this.l.update()};
A6.prototype.dispose=A6.prototype.dispose;g.C(G6,g.Q);g.h=G6.prototype;g.h.ol=function(a){this.o=a;this.O("sessionScreen",this.o)};
g.h.yd=function(a){this.ga()||(a&&H6(this,""+a),this.o=null,this.O("sessionScreen",null))};
g.h.info=function(a){j6(this.P,a)};
g.h.ry=function(){return null};
g.h.Dp=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){H6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.Dp("");G6.xa.T.call(this)};g.C(J6,G6);g.h=J6.prototype;g.h.Cp=function(a){if(this.g){if(this.g==a)return;H6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Hka(this)};
g.h.Bh=function(a){this.info("launchWithParams no-op for Cast: "+g.Lg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.yd()},this),(0,g.A)(function(){this.yd(Error("Failed to stop receiver app."))},this)):this.yd(Error("Stopping cast device witout session."))};
g.h.Dp=g.xa;g.h.T=function(){this.info("disposeInternal");g.xs(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;J6.xa.T.call(this)};
g.h.EJ=function(a,b){if(!this.ga())if(b){var c=g.Zq(b);if(g.Da(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lg(c));switch(d){case "mdxSessionStatus":I6(this,c.screenId);break;default:H6(this,"Unknown youtube message: "+d)}}else H6(this,"Unable to parse message.")}else H6(this,"No data in message.")};
g.h.ts=function(a,b,c,d){C6(this.I,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(H6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.vs((0,g.A)(this.ts,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.ry=function(){return this.g};
g.h.ZK=function(a){this.ga()||a||(H6(this,"Cast session died."),this.yd())};g.C(K6,G6);g.h=K6.prototype;g.h.Cp=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.Bh=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.xa;g.xs(this.C);this.A?this.A.stop((0,g.A)(this.yd,this,null),(0,g.A)(this.yd,this,"Failed to stop DIAL device.")):this.yd()};
g.h.T=function(){this.g();this.g=g.xa;g.xs(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;K6.xa.T.call(this)};
g.h.cL=function(a){this.ga()||a||(H6(this,"DIAL session died."),this.g(),this.g=g.xa,this.yd())};
g.h.Hn=function(a){this.K=G4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)}else this.F=(0,g.A)(function(){g.xs(this.C);this.F=g.xa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,M6(this));a(b);L6(this)},this),this.C=g.vs((0,g.A)(function(){this.F()},this),100)};
g.h.eB=function(a,b,c){C6(this.I,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.ol(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Hn(b,c)},this),(0,g.A)(function(a){H6(this,"Failed to get DIAL screen: "+a);
this.Hn(b,c)},this))};g.C(N6,G6);N6.prototype.stop=function(){this.yd()};
N6.prototype.Cp=g.xa;N6.prototype.Bh=function(){g.xs(this.g);this.g=window.NaN;var a=I4(this.I.ud(),this.l.label);a?this.ol(a):this.yd(Error("No such screen"))};
N6.prototype.T=function(){g.xs(this.g);this.g=window.NaN;N6.xa.T.call(this)};g.C(O6,g.Q);g.h=O6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Zv,this),(0,g.A)(this.sI,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.FG,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ga()||(window.chrome.cast.addReceiverActionListener(this.A),yka(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.qy,this)),this.o=T6(this),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Lg(a))},this)),this.O("yt-remote-cast2-availability-change",R6(this)),b(!0))},this),(0,g.A)(function(a){this.Ab("Failed to initialize API: "+g.Lg(a));
b(!1)},this))};
g.h.kK=function(a,b){Q6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)Q6("Unsetting old screen status: "+this.g.l.friendlyName),S6(this,null)}if(a&&b){if(!this.g){c=I4(this.l.ud(),a);if(!c){Q6("setConnectedScreenStatus: Unknown screen.");return}var d=P6(this,c);d||(Q6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(a){this.Ab("Failed to set initial custom receivers: "+g.Lg(a))},this)));
Q6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);S6(this,new N6(this.l,d),!0)}this.g.Dp(b)}else Q6("setConnectedScreenStatus: no screen.")};
g.h.lK=function(a){this.ga()?this.Ab("Setting connection data on disposed cast v2"):this.g?this.g.Bh(a):this.Ab("Setting connection data without a session")};
g.h.bL=function(){this.ga()?this.Ab("Stopping session on disposed cast v2"):this.g?(this.g.stop(),S6(this,null)):Q6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Zv,this),(0,g.A)(this.NI,this))};
g.h.T=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.qy,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Xa(g.z("yt.mdx.remote.debug.handlers_")||[],f6);g.Ze(this.g);O6.xa.T.call(this)};
g.h.Ab=function(a){j6("Controller",a)};
g.h.aw=function(a,b){this.g==a&&(b||S6(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.oI=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),Q6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)Q6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{Q6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.O("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:S6(this,
new N6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:S6(this,new K6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:S6(this,new J6(this.l,a));break;default:this.Ab("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Ab("Stopping receiver w/o session: "+a.friendlyName)}else this.Ab("onReceiverAction_ called without receiver.")};
g.h.FG=function(a){if(this.ga())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Ab("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Ab("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return Q6("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Ab('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);S6(this,new K6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.eB,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Hn,b))};
g.h.Zv=function(a){if(!this.ga()){Q6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)Q6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),S6(this,new J6(this.l,b),!0);else{this.Ab("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=I4(this.l.ud(),c.label);
d&&B4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(Q6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new J6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.aw,this,this.g)),this.g.Bh(null));this.g.Cp(a)}}};
g.h.aL=function(){return this.g?this.g.ry():null};
g.h.NI=function(a){this.ga()||(this.Ab("Failed to estabilish a session: "+g.Lg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&S6(this,null))};
g.h.sI=function(a){Q6("Receiver availability updated: "+a);if(!this.ga()){var b=R6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;R6(this)!=b&&this.O("yt-remote-cast2-availability-change",R6(this))}};
g.h.qy=function(){this.ga()||(this.o=T6(this),Q6("Updating custom receivers: "+g.Lg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.xa,(0,g.A)(function(){this.Ab("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",R6(this)))};
O6.prototype.setLaunchParams=O6.prototype.lK;O6.prototype.setConnectedScreenStatus=O6.prototype.kK;O6.prototype.stopSession=O6.prototype.bL;O6.prototype.getCastSession=O6.prototype.aL;O6.prototype.requestSession=O6.prototype.requestSession;O6.prototype.init=O6.prototype.init;O6.prototype.dispose=O6.prototype.dispose;var b7=[];j7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";k7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.ye=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
j7.prototype.isAdPlaying=function(){return 1081==this.g};
j7.prototype.clone=function(){return new j7(p7(this))};g.C(s7,g.Q);g.h=s7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.xa,A7(this,"play")):y7(this,"play"),x7(this,1,n7(t7(this))),this.O("remotePlayerChange")):v7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.xa,A7(this,"pause")):y7(this,"pause"),x7(this,2,n7(t7(this))),this.O("remotePlayerChange")):v7(this,this.pause)};
g.h.ly=function(a){if(1==this.g){if(this.l){var b=t7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.xa,A7(this,"seekTo",{newTime:a}))}else y7(this,"seekTo",{newTime:a});x7(this,3,a);this.O("remotePlayerChange")}else v7(this,g.B(this.ly,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.xa,A7(this,"stopVideo")):y7(this,"stopVideo");var a=t7(this);a.index=-1;a.videoId="";k7(a);w7(this,a);this.O("remotePlayerChange")}else v7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){j6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Ab("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){j6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Ab("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);y7(this,"setVolume",e)}c.muted=b;c.volume=a;w7(this,c)}else v7(this,g.B(this.setVolume,a,b))};
g.h.lx=function(a,b){if(1==this.g){var c=t7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Lg(b.style),g.nc(d,c.l));y7(this,"setSubtitlesTrack",d);w7(this,c)}else v7(this,g.B(this.lx,a,b))};
g.h.gq=function(a,b){if(1==this.g){y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.qb.id});var c=t7(this);c.audioTrackId=b.qb.id;w7(this,c)}else v7(this,g.B(this.gq,a,b))};
g.h.ky=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"previous")}else v7(this,g.B(this.ky,a,b))};
g.h.jy=function(a,b){if(1==this.g){if(a&&b){var c=t7(this);o7(c,a,b);w7(this,c)}y7(this,"next")}else v7(this,g.B(this.jy,a,b))};
g.h.Or=function(){1==this.g?y7(this,"dismissAutoplay"):v7(this,this.Or)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}s7.xa.dispose.call(this)};
g.h.T=function(){u7(this);this.A=null;this.B.clear();r7(this,null);s7.xa.T.call(this)};
g.h.hq=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.lI=function(a,b){this.O(a,b)};
g.h.iG=function(a){if(!a)this.dj(null),r7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=t7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,w7(this,b)}};
g.h.dj=function(a){j6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),z7(this),this.O("remotePlayerChange")};
g.h.hG=function(a){a?(z7(this),this.O("remotePlayerChange")):this.dj(null)};
g.h.vG=function(){var a=f7();a&&r7(this,a)};
g.h.Ab=function(a){j6("CP",a)};g.C(B7,g.Q);g.h=B7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Na.listId=c);this.Na.videoId=d;this.Na.index=k||0;this.Na.state=3;m7(this.Na,m);this.A="UNSUPPORTED";C7("Connecting with setPlaylist and params: "+g.Lg(l));this.g.connect({method:"setPlaylist",params:g.Lg(l)},a,O4())}else C7("Connecting without params"),
this.g.connect({},a,O4());Oka(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),D7(this,3));B7.xa.dispose.call(this)};
g.h.T=function(){E7(this);G7(this);F7(this);g.xs(this.I);this.I=window.NaN;g.xs(this.K);this.K=window.NaN;this.o=null;g.Ut(this.W);this.W.length=0;this.g.dispose();B7.xa.T.call(this);this.A=this.F=this.l=this.Na=this.g=null};
g.h.nA=function(){this.C(2)};
g.h.mG=function(){C7("Channel opened");this.R&&(this.R=!1,F7(this),this.P=g.vs((0,g.A)(function(){C7("Timing out waiting for a screen.");this.C(1)},this),15E3));
lka(wka(this.g),this.V)};
g.h.jG=function(){C7("Channel closed");(0,window.isNaN)(this.B)?R4(!0):R4();this.dispose()};
g.h.kG=function(a){R4();(0,window.isNaN)(this.G())?(C7("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,C7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),D7(this,2))};
g.h.lG=function(a){a.params?C7("Received: action="+a.action+", params="+g.Lg(a.params)):C7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Zq(a.params.devices);this.l=(0,g.G)(a,function(a){return new z4(a)});
a=!!g.Oa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,a);break;case "loungeScreenDisconnected":g.Ya(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
J7(this,!1);break;case "remoteConnected":var b=new z4(g.Zq(a.params.device));g.Oa(this.l,function(a){return b?a.id==b.id:!1})||g.Va(this.l,b);
break;case "remoteDisconnected":b=new z4(g.Zq(a.params.device));g.Ya(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":K7(this,a);break;case "nowPlaying":Rka(this,a);break;case "onStateChange":L7(this,a);break;case "onAdStateChange":Ska(this,a);break;case "onVolumeChanged":Tka(this,a);break;case "onSubtitlesTrackChanged":Qka(this,a);break;case "nowAutoplaying":Uka(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.O("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.O("autoplayModeChange",this.A);"DISABLED"==this.A&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Vka(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:C7("Unrecognized action: "+a.action)}};
g.h.ZJ=function(){if(this.o){var a=this.o;this.o=null;this.Na.videoId!=a&&H7(this,"getNowPlaying")}};
B7.prototype.subscribe=B7.prototype.subscribe;B7.prototype.unsubscribeByKey=B7.prototype.Ec;B7.prototype.ka=function(){var a=3;this.ga()||(a=0,(0,window.isNaN)(this.G())?b6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
B7.prototype.getProxyState=B7.prototype.ka;B7.prototype.C=function(a){C7("Disconnecting with "+a);E7(this);this.O("beforeDisconnect",a);1==a&&R4();a6(this.g,a);this.dispose()};
B7.prototype.disconnect=B7.prototype.C;B7.prototype.ha=function(){var a=this.Na;this.o&&(a=this.Na.clone(),o7(a,this.o,a.index));return p7(a)};
B7.prototype.getPlayerContextData=B7.prototype.ha;
B7.prototype.pa=function(a){var b=new j7(a);b.videoId&&b.videoId!=this.Na.videoId&&(this.o=b.videoId,g.xs(this.I),this.I=g.vs((0,g.A)(this.ZJ,this),5E3));var c=[];this.Na.listId==b.listId&&this.Na.videoId==b.videoId&&this.Na.index==b.index||c.push("remoteQueueChange");this.Na.g==b.g&&this.Na.volume==b.volume&&this.Na.muted==b.muted&&n7(this.Na)==n7(b)&&g.Lg(this.Na.l)==g.Lg(b.l)||c.push("remotePlayerChange");this.Na.reset(a);(0,g.D)(c,function(a){this.O(a)},this)};
B7.prototype.setPlayerContextData=B7.prototype.pa;B7.prototype.X=function(){var a=this.g.C.id,b=g.Oa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
B7.prototype.getOtherConnectedRemoteId=B7.prototype.X;B7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.F)():window.NaN};
B7.prototype.getReconnectTimeout=B7.prototype.G;B7.prototype.ca=function(){return this.A||"UNSUPPORTED"};
B7.prototype.getAutoplayMode=B7.prototype.ca;B7.prototype.Z=function(){return this.F||""};
B7.prototype.getAutoplayVideoId=B7.prototype.Z;B7.prototype.za=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.Pq(a.g);a.start()}};
B7.prototype.reconnect=B7.prototype.za;B7.prototype.na=function(a,b){H7(this,a,b);I7(this)};
B7.prototype.sendMessage=B7.prototype.na;g.C(M7,n6);g.h=M7.prototype;g.h.ud=function(a){return this.Ac.$_gs(a)};
g.h.contains=function(a){return!!this.Ac.$_c(a)};
g.h.get=function(a){return this.Ac.$_g(a)};
g.h.start=function(){this.Ac.$_st()};
g.h.add=function(a,b,c){this.Ac.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ac.$_r(a,b,c)};
g.h.Ql=function(a,b,c,d){this.Ac.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.l.length;a<b;++a)this.Ac.$_ubk(this.l[a]);this.l.length=0;this.Ac=null;M7.xa.T.call(this)};
g.h.XK=function(){this.O("screenChange")};
g.h.SH=function(){this.O("onlineScreenChange")};
A6.prototype.$_st=A6.prototype.start;A6.prototype.$_gspc=A6.prototype.YK;A6.prototype.$_gsppc=A6.prototype.oy;A6.prototype.$_c=A6.prototype.contains;A6.prototype.$_g=A6.prototype.get;A6.prototype.$_a=A6.prototype.add;A6.prototype.$_un=A6.prototype.Ql;A6.prototype.$_r=A6.prototype.remove;A6.prototype.$_gs=A6.prototype.ud;A6.prototype.$_gos=A6.prototype.ny;A6.prototype.$_s=A6.prototype.subscribe;A6.prototype.$_ubk=A6.prototype.Ec;var N7=null,O7=null,d8=null,S7=[];g.r(g8,g.I);g.h=g8.prototype;
g.h.T=function(){g.I.prototype.T.call(this);this.A.stop();this.B.stop();this.L.stop();this.R();this.g.unsubscribe("proxyStateChange",this.Xv,this);this.g.unsubscribe("remotePlayerChange",this.ej,this);this.g.unsubscribe("remoteQueueChange",this.pl,this);this.g.unsubscribe("autoplayUpNext",this.zv,this);this.g.unsubscribe("previousNextChange",this.Uv,this);this.g.unsubscribe("nowAutoplaying",this.Qv,this);this.g.unsubscribe("autoplayDismissed",this.yv,this);this.g=this.G=null};
g.h.xu=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(k8(this)){if(!t7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.K.sh(c[0],c[1]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.gq(this.l.ba(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.ya();m8(this,0==c?void 0:c);break;case "control_seek":m8(this,c[0]);break;case "control_subtitles_set_track":l8(this,c[0]);break;case "control_set_audio_track":c=c[0],k8(this)&&this.g.gq(this.l.ba(1).videoId,c)}};
g.h.gG=function(a){this.L.iA(a)};
g.h.EK=function(a){this.xu("control_subtitles_set_track",g.fc(a)?null:a)};
g.h.xx=function(){var a=this.l.Ob("captions","track");g.fc(a)||l8(this,a)};
g.h.Ov=function(a){if(k8(this)){this.g.unsubscribe("remotePlayerChange",this.ej,this);var b=Math.round(a.volume);a=!!a.muted;var c=t7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.ej,this)}};
g.h.mH=function(){g.fc(this.C)||n8(this,this.C);this.F=!1};
g.h.Xv=function(a,b){this.B.stop();2==b&&this.vx()};
g.h.ej=function(){if(k8(this)){this.A.stop();var a=t7(this.g);switch(a.g){case 1081:case 1:i8(this,new g.SD(8));this.tx();break;case 1085:case 3:i8(this,new g.SD(9));break;case 1083:case 0:i8(this,new g.SD(2));this.K.stop();h8(this,this.l.ba().lengthSeconds);break;case 1084:i8(this,new g.SD(4));break;case 2:i8(this,new g.SD(4));h8(this,n7(a));break;case -1:i8(this,new g.SD(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.R("YTP_MDX_PLAYER_ERROR")},i8(this,new g.SD(128,a))}a=t7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,n8(this,a));a=t7(this.g);-1==a.volume||Math.round(this.l.Nb())==a.volume&&this.l.isMuted()==a.muted||this.P.isActive()||this.Yx()}else j8(this)};
g.h.Uv=function(){this.l.O("mdxpreviousnextchange")};
g.h.pl=function(){k8(this)||j8(this)};
g.h.Iz=function(){this.g.Or()};
g.h.zv=function(a){a&&(a=g.Ms("/watch_queue_ajax",{method:"GET",uc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.mJ,this)}))&&(this.R=(0,g.A)(a.abort,a))};
g.h.mJ=function(a,b){var c=new g.FC({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.O("mdxautoplayupnext",c)};
g.h.Qv=function(a){(0,window.isNaN)(a)||this.l.O("mdxnowautoplaying",a)};
g.h.yv=function(){this.l.O("mdxautoplaycanceled")};
g.h.dE=function(a,b){-1==t7(this.g).g?m8(this,a):b&&this.g.ly(a)};
g.h.Yx=function(){if(k8(this)){var a=t7(this.g);this.o.Sa(this.W);a.muted?this.l.mute():this.l.Ie();this.l.setVolume(a.volume);this.W=this.o.M(this.l,"onVolumeChange",this.Ov)}};
g.h.tx=function(){this.A.stop();if(!this.g.ga()){var a=t7(this.g);1==a.g&&i8(this,new g.SD(8));h8(this,n7(a));this.A.start()}};
g.h.vx=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(q8,g.T);q8.prototype.o=function(a){p8(this,a.state)};g.r(r8,g.oT);r8.prototype.I=function(){var a=this.g.Ob("remote","receivers");a&&1<a.length&&!this.g.Ob("remote","quickCast")?(this.F=g.ob(a,this.A,this),g.pT(this,(0,g.G)(a,this.A)),a=this.g.Ob("remote","currentReceiver"),this.de(this.A(a)),this.enable(!0)):this.enable(!1)};
r8.prototype.A=function(a){return a.key};
r8.prototype.ce=function(a){return"cast-selector-receiver"==a?g.R("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
r8.prototype.Jc=function(a){g.oT.prototype.Jc.call(this,a);this.g.Tc("remote","currentReceiver",this.F[a]);this.o.rb()};g.r(s8,g.OK);g.h=s8.prototype;g.h.create=function(){$ka(g.WA(g.V(this.g)));this.C.push(g.tu("yt-remote-before-disconnect",this.dG,this));this.C.push(g.tu("yt-remote-connection-change",this.tI,this));this.C.push(g.tu("yt-remote-receiver-availability-change",this.Vv,this));this.C.push(g.tu("yt-remote-auto-connect",this.rI,this));this.C.push(g.tu("yt-remote-receiver-resumed",this.qI,this));this.Vv()};
g.h.load=function(){this.g.xo();g.OK.prototype.load.call(this);this.B=new g8(this,this.g,this.l);var a=(a=f8())?a.currentTime:0;var b=c8()?new s7(Y7(),void 0):null;0==a&&b&&(a=n7(t7(b)));0!=a&&(this.F=a||0,this.g.O("progresssync",a,void 0));o8(this,this.G,this.G);g.$U(this.g.app,6)};
g.h.unload=function(){this.g.O("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.OK.prototype.unload.call(this);g.$U(this.g.app,5)};
g.h.T=function(){g.uu(this.C);g.OK.prototype.T.call(this)};
g.h.Ui=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.xu.apply(this.B,[a].concat(g.pa(c)))};
g.h.fA=function(){return this.loaded?this.B.suggestion:null};
g.h.ye=function(){return this.l?t7(this.l).ye:!1};
g.h.hasNext=function(){return this.l?t7(this.l).hasNext:!1};
g.h.TD=function(){var a=t7(this.l),b=this.g.ba();return{allowSeeking:this.g.Cc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.F,displayedStart:-1,duration:a.C?a.I+l7(a):a.I,ingestionTime:a.C?a.A+l7(a):a.A,isPeggedToLive:1>=(a.C?a.o+l7(a):a.o)-this.F,loaded:a.K,seekableEnd:a.C?a.o+l7(a):a.o,seekableStart:0<a.B?a.B+l7(a):a.B}};
g.h.UD=function(){this.l&&this.l.jy()};
g.h.VD=function(){this.l&&this.l.ky()};
g.h.dG=function(a){1==a&&(this.K=this.l?t7(this.l):null)};
g.h.tI=function(){var a=c8()?new s7(Y7(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.K=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.ba().videoId&&this.g.au(a.videoId,n7(a)));this.g.O("videodatachange","newdata",this.g.ba(),3)};
g.h.Vv=function(){this.I=[this.o].concat(ala());var a=Z7()||this.o;t8(this,a);this.g.la("onMdxReceiversChange")};
g.h.rI=function(){var a=Z7();t8(this,a)};
g.h.qI=function(){this.A=Z7()};
g.h.SD=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.I;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?h7():t8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.I.length&&"cast-selector-receiver"==this.I[1].key?(b&&h7(),!0):!1}};
g.h.WD=function(){y7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.fc=function(){return!1};g.FQ.remote=s8;})(_yt_player);
